#!/bin/bash

appPath = "/private/tmp/com.github.cybertunnel.filevault-reissue.plist"

# Ensure the plist has the proper permissions
chown root:wheel "${appPath}"
chmod 644 "${appPath}"

# Unload to reset the RunAtLoad setting
/bin/launchctl unload "${appPath}"

# Launching the app in root context
/bin/launchctl load "${appPath}"